### ISSUE TITLE
DEGIRO (v3): Conversion fails on null value

### ISSUE THREAD

**Issue by 64knl** [dickwolff/Export-To-Ghostfolio#127]
The conversion with debug enabled fails on all lines with VAT or a service fees with the error `[e] An error ocurred [sic] while trying to retrieve an empty symbol (line XXX)!`.
```csv
04-06-2024,08:18,31-05-2024,,,B.T.W.,,EUR,-XXXX.40,EUR,XXXXX.42,
04-06-2024,08:18,31-05-2024,,,Service-fee,,EUR,-XXXX.89,EUR,XXXX.82,
21-04-2022,07:51,20-04-2022,,,DEGIRO Compensatie,,EUR,XXXX.40,EURXXXX,12,
```

After remove all those lines from the source file the conversion still fails:
```bash
/app/src/converters/degiroConverterV3.ts:239
      const numberSharesFromDescription = record.description.match(/([\d*\.?\,?\d*]+)/)[0];
                                                                                    ^


TypeError: Cannot read properties of null (reading '0')
    at DeGiroConverterV3.mapRecordToActivity (/app/src/converters/degiroConverterV3.ts:239:87)
    at <anonymous> (/app/src/converters/degiroConverterV3.ts:138:39)
```

**Comment by dickwolff** [comment]
Which version of the tool are you running? I created a new CSV file with the lines above as content, and after running the tool it gives no error and an no activities (all lines are ignored).

```json
{
    "meta": {
        "date": "2024-11-15T13:08:48.327Z",
        "version": "v0"
    },
    "activities": [],
    "updateCashBalance": false
}
```

**Comment by 64knl** [comment]
Yes, I'm running the docker version: export-to-ghostfolio@0.19.1

**Comment by dickwolff** [comment]
Thanks for confirming. Can you try and run in the same way as I did? Create a new file with just below and then run the tool?

```
04-06-2024,08:18,31-05-2024,,,B.T.W.,,EUR,-XXXX.40,EUR,XXXXX.42,
04-06-2024,08:18,31-05-2024,,,Service-fee,,EUR,-XXXX.89,EUR,XXXX.82,
21-04-2022,07:51,20-04-2022,,,DEGIRO Compensatie,,EUR,XXXX.40,EURXXXX,12,
```

If you then also no error and an empty result, there are other records that cause this.

**Comment by 64knl** [comment]
@dickwolff  Just found out that adding `--env DEBUG_LOGGING=true` will cause this issue. Without debugging it does work as expected.

**Comment by dickwolff** [comment]
I believe this is fixed with the changes in 0.20.2. There were other issues with it regarding dividends, and I think these were similar.
