### ISSUE TITLE
[Degiro exporter v1] undefined 'comment'

### ISSUE THREAD

**Issue by oregonpillow** [dickwolff/Export-To-Ghostfolio#47]
ran using docker:
`docker run -d -v ./input:/var/e2g-input -v ./output:/var/e2g-output --env GHOSTFOLIO_ACCOUNT_ID=<id here> dickwolff/export-to-ghostfolio`

```
[i] Watching /var/e2g-input..
[i] Found degiro_export.csv!
[i] Determined the file type to be of kind 'degiro'.
[i] Restored 0 ISIN-symbol pairs and 0 symbols from cache..
[i] Processing file using DeGiro converter
[i] NOTE: There is a new version available of the DeGiro converter
[i] The new converter has multiple record parsing improvements and also supports platform fees.
[i] The new converter is currently in beta and we're looking for your feedback!
[i] You can run the beta converter with the command 'npm run start degiro-v2'.
[i] Read CSV file. Start processing..
/app/src/converters/degiroConverter.ts:155
            if (result.activities[result.activities.length - 1].comment === "txfees") {
                                                                ^
TypeError: Cannot read properties of undefined (reading 'comment')
    at DeGiroConverter.<anonymous> (/app/src/converters/degiroConverter.ts:155:65)
    at Generator.next (<anonymous>)
    at fulfilled (/app/src/converters/degiroConverter.ts:6:58)
npm notice
npm notice New minor version of npm available! 10.2.4 -> 10.5.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.5.0>
npm notice Run `npm install -g npm@10.5.0` to update!
npm notice
```

running version 2 worked : `--env FORCE_DEGIRO_V2=true` in terms of no errors.

However, after checking the data there are parsing issues.

**Comment by dickwolff** [comment]
Thanks for reporting this! I'm sending this message to acknowledge the bug, but as I'm currently occupied with work I'm not able to work on the tool. I expect to have more time soon (probably friday next week) and will look into it then!

In the mean time, can you provide me with examples of the kind of data parsing issues you mention?

**Comment by dickwolff** [comment]
@oregonpillow Is this still an issue? If so, can you provide me with more details so I can look into it? Thanks!

**Comment by dickwolff** [comment]
Closing issue due to inactivity.
